version: '3'
services:
  rails: &rails
    container_name: intern-2022-rails
    build:
      context: .
      dockerfile: containers/rails/Dockerfile
      args:
        - APP_ROOT=/intern-2022
        - UID=${UID:-999}
        - GID=${GID:-999}
    command: containers/rails/entrypoint.sh
    volumes:
      - .:/intern-2022
      - bundle:/usr/local/bundle
      - node_modules:/intern-2022/node_modules # node_modules
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - "3000:3000"
    depends_on:
      - db

  webpacker:
    <<: *rails # railsから継承
    container_name: intern-2022-webpacker
    command: containers/webpacker/entrypoint.sh
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_INLINE: "true"
      WEBPACKER_DEV_SERVER_HMR: "false"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3035:3035"

  db:
    image: postgres
    container_name: intern-2022-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"

volumes:
  db-data:
  bundle:
  node_modules:
