version: '3'
services:
  web:
    container_name: intern-2022-web
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/intern-2022
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 192.168.56.2:3035
      WEBPACKER_DEV_SERVER_INLINE: "true"
      WEBPACKER_DEV_SERVER_HMR: "false"

    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db

  db:
    image: postgres
    container_name: intern-2022-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"

volumes:
  db-data:
